name: Tests
on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    container:
      image: python:latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: python -m pytest 
